### ISSUE TITLE
dbpedia docker image does not run on Apple Silicon

### ISSUE THREAD

**Issue by metalaureate** [MartinoMensio/spacy-dbpedia-spotlight#21]
Thank for your package!

Running 

```
docker run -ti \
 --platform linux/amd64 \
 --restart unless-stopped \
 --name dbpedia-spotlight.en \
 --mount source=spotlight-models,target=/opt/spotlight \
 -p 2222:80 \
 dbpedia/dbpedia-spotlight \
 spotlight.sh en
 ```
on Apple Silicon (M1) produces

>docker: Error response from daemon: driver failed programming external connectivity on endpoint dbpedia-spotlight.en (c5488172e81fe0ef796eb95b8f0eb744f1dfc15cd585cb47565515ad47ebb73b):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 2222 -j DNAT --to-destination 172.17.0.3:80:  (fork/exec /usr/sbin/iptables: no such file or directory)).

I realize this is a DBPedia/Spotlight issue but wondered with your deep knowledge if you had any pointers to a solution?

**Comment by metalaureate** [comment]
When I try to run the local install on my M1 mac I get

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.dbpedia.spotlight.db.memory.MemoryContextStore.read(MemoryContextStore.scala:122)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:363)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:355)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
        at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:166)
        at org.dbpedia.spotlight.db.memory.MemoryStore$.loadContextStore(MemoryStore.scala:195)
        at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:62)
        at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:80)
        at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
        at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:239)
        at org.dbpedia.spotlight.web.rest.Server.main(Server.java:87)
```

**Comment by metalaureate** [comment]
Increasing to -Xmx8G makes it build but then it throws all kinds of errors when you make a request. Lemme see if I can build the docker image locally and I'll delete this thread.

**Comment by metalaureate** [comment]
I was able to build the docker file locally by following the instructions at the end of this thread: https://forum.dbpedia.org/t/curl-error-52-empty-reply-from-server-when-trying-to-annotate-with-dbpedia-spotlight-docker/1454/43?page=3

The Spotlight server throws the following warnings and I don't know if they matter:

WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
Oct 30, 2022 5:51:59 PM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS

**Comment by MartinoMensio** [comment]
Hi @metalaureate,
Thank you for opening this issue. I have no personal experience with building the image for/with a M1 processor.
I can just confirm that the warning messages that you are seeing also occur in the standard docker hub image.

I am very happy you managed to build the docker image locally. I hope dbpedia publishes a working image also for M1 processors, since this is possible and works as described in the link you mentioned.

Martino
